# A list of devices you want to take the screenshots from
devices([
   "iPhone X",
   "iPhone 11 Pro Max"
])

languages([
  "en-US",
])

# The name of the scheme which contains the UI Tests
scheme("AppStoreScreenshots")

# Where should the resulting screenshots be stored?
output_directory("./AppStoreScreenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)
